stages:
  - build
  - test
  - deploy

build-backend:
    stage: build
    image: maven:3.8.3-openjdk-17
    script:
        - cd backEnd/cinema/cinema
        - echo "Building app..."
        - mvn clean
        - mvn clean install
        - echo "Finished building the app."
    artifacts:
        paths:
            - backEnd/cinema/cinema/target/cinema-0.0.8-SNAPSHOT.jar


deploy-backend:
    stage: deploy
    image: ubuntu:latest
    before_script:
        - apt-get update && apt-get install -y openssh-client
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    script: 
        - echo "Deploying started..."
        - ssh ubuntu@$EC2_IP "sudo systemctl stop myapp.service"
        - scp backEnd/cinema/cinema/target/cinema-0.0.8-SNAPSHOT.jar ubuntu@$EC2_IP:/home/ubuntu/integrador/
        - ssh ubuntu@$EC2_IP "sudo systemctl start myapp.service"
        - sleep 5s
        - echo "Deployment successful"

       